export enum Permissions {
  // Team Management
  CREATE_TEAM = 'CREATE_TEAM',
  READ_TEAM = 'READ_TEAM',
  UPDATE_TEAM = 'UPDATE_TEAM',
  DELETE_TEAM = 'DELETE_TEAM',

  // User Management
  CREATE_USER = 'CREATE_USER',
  READ_USER = 'READ_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Role Management
  CREATE_ROLE = 'CREATE_ROLE',
  READ_ROLE = 'READ_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  // Project Management
  CREATE_PROJECT = 'CREATE_PROJECT',
  READ_PROJECT = 'READ_PROJECT',
  UPDATE_PROJECT = 'UPDATE_PROJECT',
  DELETE_PROJECT = 'DELETE_PROJECT',

  // Sprint Management
  CREATE_SPRINT = 'CREATE_SPRINT',
  READ_SPRINT = 'READ_SPRINT',
  UPDATE_SPRINT = 'UPDATE_SPRINT',
  DELETE_SPRINT = 'DELETE_SPRINT',

  // Task Management
  CREATE_TASK = 'CREATE_TASK',
  READ_TASK = 'READ_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  DELETE_TASK = 'DELETE_TASK',

  // Tenant Management
  CREATE_TENANT = 'CREATE_TENANT',
  READ_TENANT = 'READ_TENANT',
  UPDATE_TENANT = 'UPDATE_TENANT',
  DELETE_TENANT = 'DELETE_TENANT',
}
