CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    deleted_at TIMESTAMP NULL,
    title VARCHAR NOT NULL,
    slug VARCHAR UNIQUE NOT NULL,
    description VARCHAR,
    status VARCHAR DEFAULT 'pending',
    start_date DATE DEFAULT '2025-07-28' NOT NULL,
    due_date DATE,
    priority VARCHAR DEFAULT 'low',
    tags JSON,
    project_id INTEGER NOT NULL,
    sprint_id INTEGER,
    parent_task_id INTEGER,
    created_by_id INTEGER,
    story_point NUMERIC(4,1) DEFAULT 0.0 NOT NULL,
    sprint_status_id INTEGER,
    project_status_id INTEGER
);

SET session_replication_role = replica;


-- Migrating Tasks to tasks
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('36', 'Handle Project to Lead Conversion', '<p><strong>Description</strong></p><p>Implement functionality to convert an external project without a lead into a lead. Ensure the system can handle multiple projects originating from a single lead.</p><br><p><strong>User Story</strong></p><p>As a system, I want to convert external projects without a lead into leads and handle multiple projects originating from a single lead.</p>', 'Completed', '2024-07-05 12:44:20', '2024-07-05 00:00:00', '1', 'Low', '2024-07-05 12:44:20', '2024-07-06 10:54:50', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('41', '<p>Custom Size Filter for Employee List View Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('e.g.', '100', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('42', '<p>Sorting Functionality for Employee List View Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, slug, story_point, created_by_id) VALUES ('e.g.', 'name', 'position', 'date of joining', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('43', '<p>Increase Minimum Employees Displayed in List View Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('44', '<p>Adjust Layout and Design for Enhanced Employee List View</p>', '<p><strong>User Story:</strong> As a user, I want the employee overview to maintain a clean and organized layout even with the increased number of employees displayed and new filtering and sorting functionalities.</p><p><br></p><p><strong>Description:</strong> Update the layout and design of the employee overview to ensure it remains user-friendly and visually appealing with the increased minimum number of employees, custom size filter, and sorting functionality. Ensure responsiveness across different devices.</p>', 'Completed', '2024-07-09 00:00:00', '2024-07-17 00:00:00', '1', 'Low', '2024-07-09 10:10:28', '2024-08-13 08:53:09', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, estimated_hours, actual_hours, slug, story_point, created_by_id) VALUES ('45', '<p>Create Super Admin Dashboard UI</p>', '<p>User Story: As a super admin, I want a dashboard that displays key metrics and reports so that I can have an overview of the platform\''s performance. Description: Develop the UI for the Super Admin Dashboard', 'including: Key metrics cards displaying \"Total Revenue\', '\"Total Clients\', '\"Subscribed Clients\', '\"Free Clients\', '\"Standard Clients\', '\"Premium Clients\". Report chart section with graphs and filters last seven days', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, slug, story_point, created_by_id) VALUES ('46', '<p>Implement Key Metrics Backend</p>', '<p>User Story: As a super admin, I need to see real-time metrics for revenue and clients so that I can monitor the platform\''s performance. Description: Develop the backend logic to fetch and calculate key metrics for the dashboard: Total Revenue Total Clients Subscribed Clients Free Clients Standard Clients Premium Clients Ensure the data is fetched from the database efficiently and accurately.</p>'',''Completed'',''2024-07-09 00:00:00'',''2024-07-11 00:00:00'',''1'',NULL,NULL,''[]'',''[]'',NULL,''Low'',''2024-07-10 06:44:22'',''2024-10-21 14:08:18'',NULL,NULL,NULL', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, estimated_hours, slug, story_point, created_by_id) VALUES ('47', '<p>Develop Report Chart Frontend</p>', '<p>User Story: As a super admin, I want to see detailed reports and graphs so that I can analyze the platform\''s performance. Description: Create the frontend components for the report chart section: Graphs displaying data for \"Subscription\', '\"Clients\', '\"Revenue\". Filters for selecting time periods last seven days', 'last month', 'custom', 'etc.', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('49', '<p>Design Super Admin Dashboard</p>', '<p><strong>Description</strong></p><p>Design and implement the Super Admin Dashboard to provide an overview of key metrics and functionalities, enabling the super admin to manage the platform effectively. The dashboard should include sections for client registration, client list, free user list, paid user list, profitability overview, payments overview, and ticket management.</p><p><br></p><p><strong>User Story</strong></p><p>As a super admin, I want a comprehensive dashboard to manage clients, users, financials, and support tickets effectively.</p>', 'Completed', '2024-07-10 09:11:55', '2024-07-10 00:00:00', '1', 'Low', '2024-07-10 09:11:55', '2024-08-15 09:34:44', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('50', '<p>Create Dashboard Layout and Key Metrics</p>', '<p><strong>Description</strong></p><p>Develop a user-friendly and responsive dashboard layout. Include key metrics cards displaying total revenue, total clients, subscribed clients, free clients, standard clients, and premium clients. Integrate report and analytics charts, and display a table of the latest clients.</p><p><br></p><p><strong>User Story</strong></p><p>As a super admin, I want to view key metrics and reports to manage the platform effectively.</p>', 'Completed', '2024-07-10 09:11:56', '2024-07-10 00:00:00', '1', 'Low', '2024-07-10 09:11:56', '2024-10-21 14:08:19', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('51', '<p>Client and User Management</p>', '<p><strong>Description</strong></p><p>Develop forms and interfaces for client registration. Implement views for displaying lists of clients, free users, and paid users. Ensure accurate display of data with filtering and searching capabilities.</p><p><br></p><p><strong>User Story</strong></p><p>As a super admin, I want to register new clients and view lists of clients and users to manage them efficiently.</p>', 'Completed', '2024-07-10 09:11:56', '2024-07-10 00:00:00', '1', 'Low', '2024-07-10 09:11:56', '2024-10-21 14:08:19', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, slug, story_point, created_by_id) VALUES ('52', '<p>Financial Overview</p>', '<p><strong>Description</strong></p><p>Implement views and dashboards to display profitability metrics and payments overview. Include charts and graphs for better visualization of financial data.</p><p><br></p><p><strong>User Story</strong></p><p>As a super admin, I want to have an overview of profitability and payments to monitor the platform\''s financial health.</p>'',''Completed'',''2024-07-10 09:11:56'',''2024-07-10 00:00:00'',''1'',NULL,NULL,''[]'',''[]'',NULL,''Low'',''2024-07-10 09:11:56'',''2024-10-21 14:08:19'',NULL,NULL,NULL', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, slug, story_point, created_by_id) VALUES ('54', '<p>Create a Responsive Dashboard for Super Admin</p>', '<p><strong>Description</strong></p><p>Develop a responsive dashboard layout that includes key metrics cards and report sections. Ensure the layout is optimized for different screen sizes and devices.</p><p><br></p><p><strong>User Story</strong></p><p>As a super admin, I want a responsive dashboard with key metrics cards and report sections, so that I can efficiently oversee and manage the platform\''s operations.</p>'',''Completed'',''2024-07-10 09:11:56'',''2024-07-10 00:00:00'',''1'',NULL,NULL,''[]'',''[]'',NULL,''Low'',''2024-07-10 09:11:56'',''2024-08-15 09:35:40'',NULL,NULL,NULL', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('55', '<p>Develop Client and User Management Functionalities</p>', '<p><strong>Description</strong></p><p>Implement functionalities for managing clients and users, including adding, editing, and deleting users. Also, provide search and filter options for easier navigation.</p><p><br></p><p><strong>User Story</strong></p><p>As a super admin, I want to manage clients and users efficiently, so that I can maintain the integrity and organization of the platform.</p>', 'Completed', '2024-07-10 09:11:56', '2024-07-10 00:00:00', '1', 'Low', '2024-07-10 09:11:56', '2024-10-21 14:08:19', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('56', '<p>Add Financial Overview Section</p>', '<p><strong>Description</strong></p><p>Develop a financial overview section on the dashboard with profitability metrics and payment visualizations, such as charts and graphs.</p><p><br></p><p><strong>User Story</strong></p><p>As a super admin, I need a financial overview with profitability metrics and payment visualizations, so that I can monitor the financial health of the platform.</p>', 'Completed', '2024-07-10 09:11:56', '2024-07-10 00:00:00', '1', 'Low', '2024-07-10 09:11:56', '2024-10-21 14:08:20', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('57', '<p>Implement Ticket Management System</p>', '<p><strong>Description</strong></p><p>Develop a ticket management system for handling client support issues, including ticket creation, assignment, status updates, and resolution tracking.</p><p><br></p><p><strong>User Story</strong></p><p>As a super admin, I need a ticket management system to handle client support issues efficiently.</p>', 'Completed', '2024-07-10 09:11:56', '2024-07-10 00:00:00', '1', 'Low', '2024-07-10 09:11:56', '2024-09-02 13:20:16', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('58', '<p>Display Latest 5 Clients <strong>Table</strong></p>', '<p><strong>Description</strong></p><p>Create a table displaying the latest 5 clients under the pie chart and reports section. Include detailed headers and a \''View All\'' link for expanded details.</p><p><br></p><p><strong>User Story</strong></p><p>As a super admin, I want to see a table showing the latest 5 clients under the pie chart and reports section, with detailed headers and a \''View All\'' link.</p>', 'Completed', '2024-07-10 09:11:56', '2024-07-10 00:00:00', '1', 'Low', '2024-07-10 09:11:56', '2024-10-21 14:08:20', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('59', '<p>Develop \''Clients Overview\'' Page</p>', '<p><strong>Description</strong></p><p>Create a \''Clients Overview\'' page with a table displaying 10 clients. Include a search bar and filters for easy navigation, as well as an \''Add Client\'' button for adding new clients.</p><p><br></p><p><strong>User Story</strong></p><p>As a super admin, I need a \''Clients Overview\'' page featuring a table displaying 10 clients, a search bar, filters, and an \''Add Client\'' button.</p>', 'Backlog', '2024-07-10 09:11:56', '2024-01-23 23:59:59', '1', 'Low', '2024-07-10 09:11:56', '2024-12-11 13:52:25', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('60', '<p>Sign up Fix Inconsistent Company Name Field and Add Restrictions</p>', '<p><strong>User Story</strong>: As a user, I need consistent field names and appropriate restrictions during the signup and settings update process, so that my information is accurately captured and managed.</p><p><br></p><p><strong>Description</strong>: Ensure there are appropriate restrictions on the second name field of the company during the signup and settings update process. Align the field names across the signup and settings pages: On the Signup page, fields should be \"First Name\" and \"Last Name\". On the Settings page, change the \"Company Name\" field to match the \"First Name\" and \"Last Name\" fields from the signup page.</p>', 'Completed', '2024-07-11 00:00:00', '2024-07-17 23:59:59', '1', 'Low', '2024-07-10 10:09:09', '2024-11-28 12:00:54', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('61', '<p>Fix Abnormal Reaction of Company Logo UI with Long Company Names</p>', '<p><strong>User Story:</strong> As a user, I need the company logo UI to handle long company names gracefully so that the interface remains visually appealing and functional.</p><p><br></p><p><br></p><p><strong>Description:</strong> Address the issue where the company logo UI reacts abnormally when the company name is too long. Ensure the UI remains visually consistent and user-friendly regardless of the length of the company name.</p>', 'Completed', '2024-07-10 00:00:00', '2024-07-17 23:59:59', '1', 'Low', '2024-07-10 10:14:51', '2024-11-28 12:01:26', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('62', '<p>Fix Erroneous \"Invalid Access Token\" Message on Successful Login Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, slug, story_point, created_by_id) VALUES ('64', '<p>Admin Sign In</p>', '<p><strong>User Story: </strong>As an admin, I want to sign in to the admin panel so that I can manage the system\''s settings and users.</p><p><br></p><ol><li>The admin must enter a valid email and password to sign in.</li><li>The admin should see an error message if the email or password is incorrect.</li><li>The admin should be redirected to the dashboard upon successful sign-in.</li></ol>'',''Completed'',''2024-07-12 00:00:00'',''2024-07-22 00:00:00'',''11'',NULL,NULL,''[]'',''[]'',NULL,''Low'',''2024-07-10 10:44:40'',''2024-10-21 14:16:37'',NULL,NULL,NULL', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('66', '<p>Add Success Message for Password Reset Email Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('67', '<p>Reset Password</p>', '<p>As an admin, I want to reset my password using the link sent to my email so that I can access my account with a new password.</p>', 'Completed', '2024-07-15 00:00:00', '2024-07-22 23:59:59', '11', 'Low', '2024-07-10 10:51:22', '2024-10-04 06:58:52', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('71', '<p>Set a New Password</p>', '<p>As an admin, I want to change a password by entering a new password and confirming the password so that I can access my account with a new password.</p>', 'Completed', '2024-07-16 00:00:00', '2024-07-22 23:59:59', '11', 'Low', '2024-07-10 13:30:23', '2024-10-04 06:59:20', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('72', '<p>History Graphs</p>', '<p>As an admin, I want to view the waste data for specific locations and custom date ranges so that I can analyze waste trends over time</p>', 'Completed', '2024-07-18 00:00:00', '2024-07-19 23:59:59', '11', 'Low', '2024-07-10 13:41:29', '2024-10-04 06:53:56', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('73', '<p>Redirect User to Login Page After Logout</p>', '<p>User Story: As a user, I need to be redirected to the login page after logging out so that I can easily log back in or switch accounts. Description: Modify the logout functionality to ensure that users are redirected to the login page instead of the landing page or signup screen after logging out. Ensure the redirection is seamless and consistent across different user roles and scenarios.</p>', 'Completed', '2024-07-10 00:00:00', '2024-07-18 00:00:00', '1', 'Low', '2024-07-10 13:43:29', '2024-08-13 08:53:03', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('74', '<p>Update Text to \"Assign Employees\" and \"No Employee Added\"</p>', '<p><strong>User Story:</strong> As a user, I need clearer instructions and messages so that I understand what actions are required and the current state of the system.</p><p><br></p><p><strong>Description:</strong> Update the text to \"Assign Employees\" to provide clearer instructions to the user. Change the text from “No Options” to “No Employee Added” to better reflect the current state when there are no employees.</p>', 'Completed', '2024-07-10 00:00:00', '2024-07-19 00:00:00', '1', 'Low', '2024-07-10 13:47:03', '2024-08-13 08:03:48', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('75', '<p>Ensure Consistent Vertical Padding, Alert Message Positioning, and Dropdown Styles in Add Employee form</p>', '<p><strong>User Story: </strong>As a user, I need a consistent and visually appealing Add Employee side panel so that the form is easy to read and interact with.</p><p><br></p><p><strong>Description:</strong> Ensure consistent vertical padding between all fields in the Add Employee side panel. Position alert messages to start from the corresponding field. Standardize the dropdown icon, placeholder, and their colors across all input fields.</p>', 'Completed', '2024-07-10 00:00:00', '2024-07-19 00:00:00', '1', 'Low', '2024-07-10 13:58:01', '2024-08-13 08:55:34', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('76', '<p>Improve Edit Functionality for Test Cases Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('77', '<p>Implement Confirmation Alert for Deletions</p>', '<p><strong>User Story:</strong> As a user, I need a confirmation alert before any deletion action so that I can avoid accidental deletions and confirm my intention to delete.</p><p><br></p><p><strong>Description</strong>: Implement a confirmation alert that appears before any deletion action within the system. Ensure that users must confirm the deletion before the action is executed. Apply the confirmation alert consistently across all deletion actions, including test cases.</p>', 'Completed', '2024-07-11 00:00:00', '2024-07-18 00:00:00', '1', 'Low', '2024-07-10 14:15:19', '2024-10-21 14:08:20', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('79', '<p>Review and Improve \"Update Task\" Button Functionality</p>', '<p><strong>User Story:</strong> As a user, I need the \"Update Task\" button to have a clear purpose and functionality so that task updates are processed and saved effectively.</p><p><br></p><p><strong>Description</strong>: Evaluate the current functionality of the \"Update Task\" button in the task pop-up. Ensure that updates to tasks require the use of the \"Update Task\" button to be saved. Provide clear feedback to users indicating when updates are successfully saved.</p>', 'Completed', '2024-07-10 00:00:00', '2024-07-19 00:00:00', '1', 'Low', '2024-07-10 14:59:01', '2024-08-13 08:52:31', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('80', '<p>Restrict Comment Section to Vertical Stretch Only Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('81', '<p>Restrict Year Input to Four Digits in Date Fields Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('83', '<p>Add Confirmation Alert for Pop-Up Closure Fail', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('84', '<p>Standardize Company Logo Appearance to Match Profile Picture</p>', '<p><strong>User Story</strong>: As a user, I need the company logo to appear similar to the profile picture, so that the interface has a consistent and professional look.</p><p><br></p><p><strong>Description</strong>: Modify the appearance of the company logo to match the design and style of the profile picture. Ensure that the company logo is displayed with the same size, shape, and border styles as the profile picture. Maintain a consistent look and feel across the application.</p>', 'Completed', '2024-07-11 00:00:00', '2024-07-19 00:00:00', '1', 'Low', '2024-07-11 09:17:58', '2024-08-13 08:30:11', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('85', '<p>Fix Client Name Display on Project Info Icon Click Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('86', '<p>Allow Same Start and End Date for Task Creation Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('87', '<p>Add Placeholder to Priority Field in Add Task Pop-Up Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, slug, story_point, created_by_id) VALUES ('Select', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, slug, story_point, created_by_id) VALUES ('Select', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('88', '<p>Fix Label Color and Error Issues After Moving Ticket Twice</p>', '<p><strong>User Story:</strong> As a user, I need the label color to remain consistent and the ability to add more labels even after moving a ticket twice, so that the ticket management process is smooth and error-free.</p><p><br></p><p><strong>Description:</strong> Fix the issue where the label color changes to black after moving a ticket twice. Ensure that users can continue to add more labels after moving a ticket twice. Address the error message “Lock wait timeout exceeded, try restarting transaction” that appears occasionally.</p>', 'Completed', '2024-07-12 00:00:00', '2024-07-19 23:59:59', '1', 'Low', '2024-07-11 09:28:55', '2024-11-28 12:00:16', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, slug, story_point, created_by_id) VALUES ('89', '<p>Adjust Notification Text Format</p>', '<p><strong>User Story</strong>: As a user, I need the notification text to be clear and correctly formatted, so that I can easily understand who made updates.</p><p><br></p><p><strong>Description</strong>: Adjust the notification text format from \"updated {name}\" to \"updated by {name}\". Ensure that the new format is applied consistently across all notifications. Verify that the user\''s name is displayed correctly in the notification text.</p><p>grgr</p>'',''Completed'',''2024-07-11 00:00:00'',''2024-07-19 00:00:00'',''1'',NULL,NULL,''[\"Frontend\', '\"Backend\"]'',''[]'',NULL,''Low'',''2024-07-11 09:33:10'',''2024-08-13 08:03:44'',NULL,NULL,NULL', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('90', '<p>Waste Composition Pie Chart</p>', '<p>As an admin, I want to view a pie chart of waste composition for a specific location and custom date range so that I can understand the distribution of different types of waste.</p>', 'Completed', '2024-07-19 00:00:00', '2024-07-20 23:59:59', '11', 'Low', '2024-07-11 10:01:07', '2024-10-04 06:59:44', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('91', '<p>Edit Profile Page</p>', '<p>As a user, I want to edit my profile information, specifically my username and profile picture, so that I can keep my profile up-to-date and personalize my account.</p>', 'Completed', '2024-07-21 00:00:00', '2024-07-22 23:59:59', '11', 'Low', '2024-07-11 10:02:23', '2024-10-04 06:58:07', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('93', '<p>Implement Payments Overview Feature</p>', '<p><strong>Description</strong></p><p>Develop a Payments Overview feature that enables administrators to view and manage a comprehensive list of payment invoices including Invoice Number, Date, Amount, Name, Company, and Status. Allow sorting and filtering of invoices based on various attributes.</p><p><br></p><p><strong>User Story</strong></p><p>As an administrator, I want to have a detailed record of all payment transactions so that I can track and manage payment histories and statuses.</p>', 'Completed', '2024-07-11 11:07:15', '2024-07-11 00:00:00', '1', 'Low', '2024-07-11 11:07:15', '2024-09-02 13:20:16', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('94', '<p>Create Plan Management Feature</p>', '<p><strong>Description</strong></p><p>Develop a Plan Management feature that allows administrators to manage subscription plans. This includes functionality for viewing, adding, and editing plans with details such as Title, Price, Duration, Number of Users, Employees, Leads, Projects, Storage, AI Generated User Stories, Support Type, and Price for the plan.</p><p><br></p><p><strong>User Story</strong></p><p>As an administrator, I want to manage various subscription plans including adding, editing, and viewing plan details so that I can offer different plans to clients.</p>', 'Completed', '2024-07-11 11:07:16', '2024-07-11 00:00:00', '1', 'Low', '2024-07-11 11:07:16', '2024-09-02 13:20:16', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('95', '<p>Implement Add Plan Form</p>', '<p><strong>Description</strong></p><p>Develop an Add Plan Form that allows administrators to create new subscription plans. The form includes fields for Title, Users, Employees, Leads, Projects, Storage, AI Generated User Stories, Support, Price, and Document Character number.</p><p><br></p><p><strong>User Story</strong></p><p>As an administrator, I want to add new subscription plans via a form so that I can expand the offerings to clients.</p>', 'Completed', '2024-07-11 11:07:17', '2024-07-11 00:00:00', '1', 'Low', '2024-07-11 11:07:17', '2024-09-02 13:20:16', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('96', '<p>Create Tickets Overview Feature Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, slug, story_point, created_by_id) VALUES ('98', '<p>Adjust Sidebar Logo Position Pass', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('99', '<p>Implement \"Mark as Read\" Feature in Notifications</p>', '<p>User Story: As a user, I need the \"Mark as Read\" button in notifications to function correctly so that I can manage my notifications effectively. Description: Currently, clicking on the \"Mark as Read\" button in notifications does not perform any action. Implement the functionality to mark notifications as read when the button is clicked.</p>', 'Completed', '2024-07-12 00:00:00', '2024-07-19 00:00:00', '1', 'Low', '2024-07-12 11:47:56', '2024-08-13 08:55:51', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('100', '<p>Google authentication</p>', '<p>Social login/signup</p>', 'Completed', '2024-07-16 00:00:00', '2024-07-23 00:00:00', '1', 'High', '2024-07-15 08:07:47', '2024-08-27 14:42:44', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('102', 'Make email templates', 'design an email templates for ontezo mails', 'Completed', '2024-07-16 00:00:00', '2024-07-17 00:00:00', '1', 'Low', '2024-07-15 08:31:39', '2024-07-18 12:59:40', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('103', '<p>Forgot Password</p>', '<p><strong>User Story:</strong> As an admin, I want to reset my password if I forget it so that I can regain access to my account.</p>', 'Completed', '2024-07-19 00:00:00', '2024-07-22 23:59:59', '11', 'Low', '2024-07-15 09:50:52', '2024-10-04 06:55:22', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, slug, story_point, created_by_id) VALUES ('104', '<p>Dashboard Metrics</p>', '<p>As an admin, I want to view various metrics on the dashboard so that I can monitor and analyze the system\''s performance and usage.</p><p><br></p><p><strong>Description: </strong></p><p><br></p><p>Three key metrics</p><ul><li>Total Users</li><li>Total Engagement</li><li>Total Reports</li></ul>'',''Completed'',''2024-07-22 00:00:00'',''2024-07-23 23:59:59'',''11'',NULL,NULL,''[]'',''[]'',NULL,''Low'',''2024-07-15 11:06:29'',''2024-10-04 07:00:01'',NULL,NULL,NULL', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('3231', 'Implement Login API', '<p>As a user, I want to be able to log in to the system using my credentials, so that I can access my account and perform authorized actions.</p><p><strong>Acceptance Criteria:</strong></p><ul><li>The API should accept a username and password.</li><li>Upon successful login, it should return an authentication token.</li><li>If the credentials are invalid, it should return an appropriate error message.</li><li>If required fields are missing, it should return a validation error.</li></ul><p><br></p>', 'Completed', '2025-01-30 00:00:00', '2025-01-30 23:59:59', 'fc221e37-1fc2-4448-8e89-109265e17814', 'High', '2025-01-30 10:30:09', '2025-04-21 05:15:09', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, slug, story_point, created_by_id) VALUES ('3232', 'List Clients API', '<p>As a user, I want to be able to view a list of all clients, so that I can manage and review client information efficiently.</p><p><strong>Acceptance Criteria:</strong></p><ul><li>The API should return a paginated list of clients.</li><li>It should support query parameters for pagination e.g., page number and limit', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, slug, story_point, created_by_id) VALUES ('3233', 'Create New Client API', '<p>As a user, I want to be able to create a new client, so that I can add new clients to the system.</p><p><strong>Acceptance Criteria:</strong></p><ul><li>The API should accept client details such as name, email, and phone number.</li><li>Upon successful creation, it should return the newly created client\''s information.</li><li>If required fields are missing or if the email already exists', 'it should return appropriate error messages.</li></ul><p><br></p>'',''Completed'',''2025-01-30 00:00:00'',''2025-01-30 23:59:59'',''fc221e37-1fc2-4448-8e89-109265e17814'',NULL,NULL,''[\"Backend\"]'',''[]'',NULL,''High'',''2025-01-30 10:32:21'',''2025-04-21 05:14:55'',NULL,NULL,NULL', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('3234', 'View Client API', '<p>As a user, I want to be able to view detailed information about a specific client, so that I can review and manage individual client records.</p><p><strong>Acceptance Criteria:</strong></p><ul><li>The API should accept a client ID as a parameter.</li><li>It should return detailed information about the specified client.</li><li>If the client ID is invalid or the client does not exist, it should return an appropriate error message.</li></ul><p><br></p>', 'Completed', '2025-01-30 00:00:00', '2025-01-30 23:59:59', 'fc221e37-1fc2-4448-8e89-109265e17814', 'High', '2025-01-30 10:33:11', '2025-04-21 05:14:20', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('3235', 'Go through and define inventory module scope', '', 'Completed', '2025-01-30 00:00:00', '24', 'Medium', '2025-01-30 10:34:21', '2025-04-23 13:04:24', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('3236', 'Fix invitation accept issue in staging', '', 'Completed', '2025-01-30 00:00:00', '24', 'Medium', '2025-01-30 10:36:07', '2025-04-23 13:04:24', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('3237', 'Disable button during API calling', '', 'Completed', '2025-01-30 00:00:00', '24', 'Medium', '2025-01-30 10:37:07', '2025-04-23 13:04:24', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('3238', 'Delete Client API', '<p>As a user, I want to be able to delete a client, so that I can remove clients who are no longer active or needed in the system.</p><p><strong>Acceptance Criteria:</strong></p><ul><li>The API should accept a client ID as a parameter.</li><li>Upon successful deletion, it should return a confirmation message.</li><li>If the client ID is invalid or the client does not exist, it should return an appropriate error message.</li></ul><p><br></p>', 'Completed', '2025-01-30 00:00:00', '2025-01-30 23:59:59', 'fc221e37-1fc2-4448-8e89-109265e17814', 'High', '2025-01-30 10:45:49', '2025-04-21 05:14:41', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, slug, story_point, created_by_id) VALUES ('3239', 'Integrate Login API with Frontend', '<p>As a user, I want to be able to log in to the system using my credentials, so that I can access my account and perform authorized actions.</p><p><strong>Acceptance Criteria:</strong></p><ul><li>The frontend login form should send a POST request to the <span style=\"color: var--text-primary', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6009', 'Wellfound - Scrapping', '<p><a href=\"https://wellfound.com/recruit/pricing/\" rel=\"noopener noreferrer\" target=\"_blank\">https://wellfound.com/</a></p>', 'Completed', '2025-06-13 00:00:00', 'a62a5b12-8bd4-4de7-9289-5332bd42194b', 'Low', '2025-06-13 11:49:06', '2025-07-03 15:02:34', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6010', 'DiversityJobs - Scrapping ', '<p><a href=\"https://www.diversityjobs.com/post-a-job/\" rel=\"noopener noreferrer\" target=\"_blank\">https://www.diversityjobs.com/post-a-job/</a></p>', 'Completed', '2025-06-13 00:00:00', 'a62a5b12-8bd4-4de7-9289-5332bd42194b', 'Low', '2025-06-13 11:49:24', '2025-07-03 15:02:33', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6011', 'US Jobs - Scrapping', '<p><a href=\"https://www.usajobs.gov/\" rel=\"noopener noreferrer\" target=\"_blank\">https://www.usajobs.gov/</a></p>', 'Completed', '2025-06-13 00:00:00', 'a62a5b12-8bd4-4de7-9289-5332bd42194b', 'Low', '2025-06-13 11:49:41', '2025-07-03 15:02:31', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6012', 'Jooble - Scrapping', '<p><a href=\"https://jooble.org/jobs-online\" rel=\"noopener noreferrer\" target=\"_blank\">https://jooble.org/jobs-online</a></p>', 'Completed', '2025-06-13 00:00:00', 'a62a5b12-8bd4-4de7-9289-5332bd42194b', 'Low', '2025-06-13 11:49:56', '2025-07-03 15:02:29', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6013', 'Job2Careers - Scrapping', '<p><a href=\"https://www.jobs2careers.com/\" rel=\"noopener noreferrer\" target=\"_blank\">https://www.jobs2careers.com/</a></p>', 'Completed', '2025-06-13 00:00:00', 'a62a5b12-8bd4-4de7-9289-5332bd42194b', 'Low', '2025-06-13 11:50:09', '2025-07-03 15:02:27', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6014', 'Remotejobs - Scrapping ', '<p><a href=\"https://www.remotejobs.io/\" rel=\"noopener noreferrer\" target=\"_blank\">https://www.remotejobs.io/</a></p>', 'Completed', '2025-06-13 00:00:00', 'a62a5b12-8bd4-4de7-9289-5332bd42194b', 'Low', '2025-06-13 11:50:43', '2025-07-03 15:02:25', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6015', 'Flexjobs - Scrapping', '<p><a href=\"https://www.flexjobs.com/homevariant/t1\" rel=\"noopener noreferrer\" target=\"_blank\">https://www.flexjobs.com/</a></p>', 'Completed', '2025-06-13 00:00:00', 'a62a5b12-8bd4-4de7-9289-5332bd42194b', 'Low', '2025-06-13 11:51:06', '2025-07-03 15:02:23', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6016', 'Turing - Scrapping', '<p><a href=\"https://www.turing.com/jobs/remote-jobs-in-pakistan\" rel=\"noopener noreferrer\" target=\"_blank\">https://www.turing.com</a></p>', 'Completed', '2025-06-13 00:00:00', 'a62a5b12-8bd4-4de7-9289-5332bd42194b', 'Low', '2025-06-13 11:51:37', '2025-07-03 15:02:22', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, slug, story_point, created_by_id) VALUES ('6018', 'Fixes at database and project deps and setup', '<ul><li>Fixed the storage issues for the account</li><li>Removed the useless acounts from the database.testing account', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6019', 'weworkremotely - Scrapping ', '<p><a href=\"https://weworkremotely.com/\" rel=\"noopener noreferrer\" target=\"_blank\">https://weworkremotely.com/</a></p>', 'Completed', '2025-06-13 00:00:00', 'a62a5b12-8bd4-4de7-9289-5332bd42194b', 'Low', '2025-06-13 11:52:08', '2025-07-03 15:02:20', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6020', 'Remote - Scrapping', '<p><a href=\"https://remote.co/\" rel=\"noopener noreferrer\" target=\"_blank\">https://remote.co/</a></p>', 'Completed', '2025-06-13 00:00:00', 'a62a5b12-8bd4-4de7-9289-5332bd42194b', 'Low', '2025-06-13 11:52:29', '2025-07-03 15:02:18', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6021', 'iOS - \"Password Reset Token Expired\" Error on Change Password Screen After Successful Code Verification', '<p><strong>Description:</strong> After successfully verifying a password reset code, the user encounters a \"Password Reset Token Expired\" error on the \"Change Password\" screen. This prevents the user from setting a new password, despite having already passed the verification step. This error should not occur after successful code verification, and the user should be able to update their password.</p><p><strong>Steps to Reproduce:</strong></p><ol><li>Initiate the password reset process.</li><li>Successfully verify the password reset code.</li><li>Navigate to the \"Change Password\" screen.</li><li>Attempt to set a new password.</li><li>Observe the error message.</li></ol><p><br></p>', 'Completed', '2025-06-13 00:00:00', '912df8f1-f47e-41d7-bc55-a10a76d1892e', 'Low', '2025-06-13 11:54:45', '2025-06-19 10:55:04', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, due_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6022', 'PR Reviews and code merge for the email template issue', 'PR Reviews and code merge for the email template issue', 'Completed', '2025-06-13 00:00:00', '2025-06-12 23:59:59', '580e4bd4-8fc0-4222-97e8-d40fa0561969', 'Low', '2025-06-13 11:56:22', '2025-06-13 11:58:41', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
INSERT INTO tasks (id, title, description, status, start_date, project_id, priority, created_at, updated_at, slug, story_point, created_by_id) VALUES ('6023', 'iOS -  \"Invalid Prisma Unique Constraints\" Error During Habit Creation', '<p><strong>Description:</strong> The application displays an \"Invalid Prisma Unique Constraints\" error when a user attempts to create a new habit. This error prevents the creation of new habits, a core functionality of the app. This error should be resolved, and users should be able to create new habits without issue.</p><p><strong>Steps to Reproduce:</strong></p><ol><li>Open the application.</li><li>Navigate to the \"Create Habit\" screen.</li><li>Enter the details for a new habit.</li><li>Attempt to save the new habit.</li><li>Observe the error message.</li></ol><p><br></p>', 'Completed', '2025-06-13 00:00:00', '912df8f1-f47e-41d7-bc55-a10a76d1892e', 'Low', '2025-06-13 11:57:29', '2025-06-18 12:48:03', LOWER(REPLACE(title, ' ', '-')), 0.0, 1);
