CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    deleted_at TIMESTAMP NULL,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    otp_code VARCHAR,
    is_email_verified BOOLEAN DEFAULT FALSE,
    is_password_forget BOOLEAN DEFAULT FALSE,
    otp_expiry TIMESTAMP,
    tenant_id INTEGER,
    timezone VARCHAR,
    last_login TIMESTAMPTZ,
    is_agree_terms BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    is_deleted BOOLEAN DEFAULT FALSE
);


-- Temporarily disable foreign key checks
SET session_replication_role = replica;


-- Migrating Employees to users
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('1', 'muntaha@abark.pk', true, '2024-07-05 06:12:44', '2025-06-11 11:58:42', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('2', 'zohaib_mughal@abark.pk', true, '2024-07-05 06:17:46', '2024-12-13 12:26:33', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('3', 'ahmed_irfan@abark.pk', true, '2024-07-05 10:38:01', '2024-12-13 13:26:33', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('4', 'afaq@abark.pk', true, '2024-07-05 10:39:23', '2025-02-03 06:33:05', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('5', 'raheel@abark.pk', true, '2024-07-05 10:41:15', '2025-06-11 12:02:31', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('6', 'ahmad_fraz@abark.pk', true, '2024-07-05 10:43:55', '2024-11-05 11:31:45', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('7', 'tehreem@abark.pk', true, '2024-07-05 11:28:30', '2025-06-11 12:01:50', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('8', 'rao_usama@abark.pk', true, '2024-07-05 11:29:57', '2025-06-11 11:35:09', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('9', 'md@abark.pk', true, '2024-07-05 11:31:06', '2024-12-26 09:35:11', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('11', 'asad@abark.pk', true, '2024-07-08 13:29:20', '2025-06-05 12:26:43', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('12', 'sadaf@abark.pk', true, '2024-07-08 13:33:18', '2024-11-20 08:43:08', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('14', 'safiullah@abark.pk', true, '2024-07-08 13:38:39', '2024-12-13 12:28:54', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('18', 'junaid@abark.pk', true, '2024-07-08 14:03:40', '2024-12-13 12:56:29', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('19', 'hasnain@abark.pk', true, '2024-07-08 14:07:36', '2024-12-25 11:25:43', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('20', 'mahmood@abark.pk', true, '2024-07-08 14:09:14', '2024-12-13 12:54:54', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('25', 'asad_ghafoor@abark.pk', true, '2024-07-08 14:34:09', '2024-12-13 13:25:11', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('26', 'moeed@abark.pk', true, '2024-07-08 14:36:05', '2025-01-01 13:59:15', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('28', 'faizan@abark.pk', true, '2024-07-08 14:40:42', '2024-12-13 13:01:04', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('29', 'nawaz@abark.pk', true, '2024-07-08 14:42:36', '2025-06-29 15:54:35', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('33', 'ahsham@abark.pk', true, '2024-07-08 14:54:21', '2024-12-13 13:25:44', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('34', 'shoaib@abark.pk', true, '2024-07-08 14:56:00', '2024-12-13 12:47:15', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('37', 'wjeeh@abark.pk', true, '2024-07-09 05:02:29', '2025-01-31 14:18:07', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('38', 'eman-munir@abark.pk', true, '2024-07-09 05:03:48', '2024-12-13 13:24:17', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('39', 'abarkpk@gmail.com', true, '2024-07-09 05:24:24', '2024-07-09 05:24:42', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('40', 'qasim@abark.pk', true, '2024-07-09 12:06:13', '2025-02-03 06:28:57', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('41', 'moeez-ur-rehman@abark.pk', true, '2024-08-05 05:56:07', '2025-07-03 10:52:07', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('42', 'adnan_haider@abark.pk', true, '2024-08-06 07:05:28', '2024-12-13 13:27:45', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('47', 'abdul_rehman@abark.pk', true, '2024-08-06 10:43:41', '2025-01-27 14:37:01', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('48', 'ahsan_raza@abark.pk', true, '2024-08-06 10:48:48', '2025-05-14 11:19:37', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('49', 'bakhtawar@abark.pk', true, '2024-08-06 10:55:25', '2025-04-15 10:22:26', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('50', 'asadghafoor2003@gmail.com', true, '2024-07-08 14:34:09', '2024-12-13 13:25:01', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('53', 'ali_hassan@abark.pk', true, '2024-09-19 11:30:37', '2025-04-09 14:32:09', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('54', 'hasnain_hamid@abark.pk', true, '2024-09-19 11:47:25', '2024-12-13 12:52:04', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('55', 'kashuf_naeem@abark.pk', true, '2024-09-25 12:50:00', '2024-12-13 12:55:33', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('58', 'tahir.manzoor@abark.pk', true, '2024-11-20 12:36:45', '2025-01-01 11:51:04', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('59', 'waleed.ahmad@abark.pk', true, '2024-11-20 12:36:45', '2025-06-04 10:45:37', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('60', 'muhammad.rafay@abark.pk', true, '2024-11-20 12:36:45', '2025-06-11 11:57:57', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('66', 'adnan.mushtaq@abark.pk', true, '2024-12-04 06:32:49', '2024-12-13 13:27:17', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('70', 'abdul.muqeet@abark.pk', true, '2025-01-01 07:54:49', '2025-06-11 11:35:38', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('71', 'kamran.aslam@abark.pk', true, '2025-01-01 10:21:46', '2025-06-12 11:20:23', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('76', 'haider.sajjad@abark.pk', true, '2025-01-30 07:51:03', '2025-04-25 07:39:00', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('78', 'philip@utilauditors.com', true, '2025-02-03 07:09:36', '2025-02-10 04:19:37', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('86', 'bilal.amir@abark.pk', true, '2025-03-03 10:24:21', '2025-06-11 12:07:08', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('88', 'azib.gondal@abark.pk', true, '2025-03-17 06:51:30', '2025-06-11 12:07:59', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('89', 'sikander.zubair@abark.pk', true, '2025-04-09 11:27:56', '2025-05-07 07:12:30', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('91', 'raza.liaqat@abark.pk', false, '2025-04-22 08:22:20', '2025-06-11 11:48:45', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('92', 'qasim.ashraf@abark.pk', true, '2025-04-30 06:31:44', '2025-06-11 11:58:26', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('93', 'ahmad.naeem@abark.pk', true, '2025-04-30 06:32:01', '2025-07-07 13:01:31', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('95', 'wajeeha.khalid@abark.pk', true, '2025-05-05 06:35:51', '2025-05-05 10:53:05', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('96', 'adeel.ahmed@abark.pk', true, '2025-05-05 06:43:02', '2025-06-27 12:32:08', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('97', 'faizan.asif@abark.pk', false, '2025-05-05 06:43:57', '2025-06-11 12:06:54', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('98', 'ali.akram@abark.pk', true, '2025-05-12 08:22:05', '2025-06-16 08:29:21', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('99', 'muhammad.hammad@abark.pk', true, '2025-05-12 08:22:14', '2025-05-14 10:05:53', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('100', 'noman.rafique@abark.pk', true, '2025-05-13 05:19:10', '2025-06-12 08:10:21', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('101', 'asfand.yar@abark.pk', true, '2025-05-19 05:37:51', '2025-07-16 13:08:22', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('102', 'abdullah.sqa@abark.pk', true, '2025-05-26 10:05:05', '2025-06-11 12:10:26', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('104', 'hania.arshad@abark.pk', true, '2025-05-26 10:10:15', '2025-06-11 12:06:11', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('105', 'masood.tariq@abark.pk', true, '2025-05-26 10:10:35', '2025-06-11 12:04:39', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('106', 'awais.raza@abark.pk', true, '2025-06-02 07:06:32', '2025-06-12 10:08:32', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('107', 'sharjeel.tariq@abark.pk', true, '2025-06-02 07:06:42', '2025-06-11 11:47:55', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('108', 'ali.hamza@abark.pk', true, '2025-06-10 06:49:00', '2025-06-12 12:15:17', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('109', 'nimra.haider@abark.pk', true, '2025-06-10 10:06:57', '2025-06-11 12:04:02', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('110', 'hamza.safwan@abark.pk', true, '2025-06-23 08:14:04', '2025-06-23 08:17:47', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('111', 'shehroz.ahmed@abark.pk', true, '2025-06-30 14:53:11', '2025-07-17 10:44:09', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('112', 'hafiz.ali.haider@abark.pk', true, '2025-07-04 13:24:22', '2025-07-07 06:33:17', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('113', 'muhammad.sheraz@abark.pk', true, '2025-07-07 08:10:39', '2025-07-07 08:16:33', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('114', 'ahmad.ali@abark.pk', true, '2025-07-14 07:49:41', '2025-07-14 07:55:06', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('116', 'ali.ramis@abark.pk', true, '2025-07-21 06:35:11', '2025-07-21 07:07:01', true, NULL, false, true, false, 'default_password_hash', 1);
INSERT INTO users (id, email, is_active, created_at, updated_at, is_email_verified, otp_code, is_password_forget, is_agree_terms, is_deleted, password, tenant_id) VALUES ('117', 'zohaib@yopmail.com', true, '2025-07-30 08:06:24', '2025-07-30 08:07:47', true, NULL, false, true, false, 'default_password_hash', 1);
